### ISSUE TITLE
conda install error

### ISSUE THREAD

**Issue by AlicePsyche** [churchill-lab/g2gtools#1]
Hi, 

I am trying to install g2gtools using conda as `(g2gtools) $ conda install -c kbchoi g2gtools` but I received error report says 

``` bash
Error:  Dependencies missing in current linux-64 channels:
  - g2gtools -> bx-python >=0.7.2
  - g2gtools -> pysam >=0.8.3
```

Could you please check if you have provided all the needed dependencies in conda? 

Thanks in advance. :)

**Comment by kbchoi-jax** [comment]
Go back to the root environment first

```
(g2gtools) $ source deactivate
```

and do the following,

```
$ conda config --add channels r
$ conda config --add channels bioconda
```

and then try install again.

```
$ source activate g2gtools
(g2gtools) $ conda install -c kbchoi g2gtools
```

**Comment by AlicePsyche** [comment]
Thanks a lot ! I have installed it successfully. Sorry for the silly question, I am not familiar with conda...
