### ISSUE TITLE
Unable to Generate Correct *.chain file for Inbred Mouse Strains

### ISSUE THREAD

**Issue by rantingswede373** [churchill-lab/g2gtools#13]
I'm attempting to use g2gtools to convert coordinates between two inbred mouse strains (C57Bl/6J and CAST/EiJ) following the documentation online. If I ignore Indels it seems to work fine with the patched genome reflecting known variants in a few quick spot checks. The generation of the chain file for coordinate conversion does not seem to be working however, as the file is very small and a test run with a signal bed file returns the same coordinates as in the original reference despite there being millions of Indel variants between the two.

I'm using version 0.1.3 with the relevant command being:
g2gtools vcf2chain --pass -f NCBIM37_um.fa -i mgp.v2.indels.annot.reformat.vcf.gz -s CASTEiJ -o mm9-to-CASTEiJ.chain

This returns a stdout as below:
`Chromosome: 1
STATISTICS
Chromosome: 10
STATISTICS
Chromosome: 11
STATISTICS
...
...
complete
Parsed 0 total lines
Chain file created
Execution complete: 00:00:10.13
`

So obviously something is off, although no explicit error messages come up. I confirmed that the strain is indeed "CASTEiJ" and not "CAST_EiJ" or some other variant as well as any other small issues that may have led to this. I'd like to try version 0.2.0, but haven't been able to successfully install it. Any help would be greatly appreciated!

**Comment by kbchoi-jax** [comment]
I think Sanger vcf files use `CAST_EiJ` as a strain name. Anyways I still highly recommend using v0.2.0. Please try my new documentation and let me know how the installation fails.

http://churchill-lab.github.io/g2gtools/#installation

**Comment by rantingswede373** [comment]
If I change the --pass filter to --quality it appears to work. I'll have to double check the numbers to be sure they make sense, but it's at least generating statistics for each chromosome and the chain file is ~83 MB. Sorry, I thought I had checked that before posting.

At least from the source I have I think CASTEiJ is correct though:
`curl ftp://ftp-mouse.sanger.ac.uk/REL-1211-SNPs_Indels/mgp.v2.indels.annot.reformat.vcf.gz --output mgp.v2.indels.annot.reformat.vcf.gz
gunzip mgp.v2.indels.annot.reformat.vcf.gz
grep -v '##' mgp.v2.indels.annot.reformat.vcf | head

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	129S1	AJ	AKR	BALBcJ	C3HHeJ	C57BL6NJ	CASTEiJ	CBAJ	DBA2J	FVB_NJ	LPJ	NODShiLtJ	NZO	PWKPhJ	Spretus	WSBEiJ`

**Comment by kbchoi-jax** [comment]
Sorry I never tested `g2gtools` with those old versions. I note they released REL-1807 recently.
