### ISSUE TITLE
what vcf file to input to g2gtools v0.2.7 vcf2vci -i? indels or snps? or both?

### ISSUE THREAD

**Issue by xiaodongpang23** [churchill-lab/g2gtools#16]
Based on the user guide https://g2gtools.readthedocs.io/en/latest/usage.html
VCF indels is the vcf file to vcf2chain and VCF snps is for patch as follow:
g2gtools vcf2chain -f ${REF} -i ${VCF_INDELS} -s ${STRAIN} -o ${STRAIN}/REF-to-${STRAIN}.chain
g2gtools patch -i ${REF} -s ${STRAIN} -v ${VCF_SNPS} -o ${STRAIN}/${STRAIN}.patched.fa

However, in the g2gtools v0.27, there is no vcf2chain but only vcf2vci. So what vcf file should I input to g2gtools vcf2vci -i? indels or snps? or both?

Update the user guide to the latest version would be appreciated.

**Comment by kbchoi-jax** [comment]
Use both, for example, '-i <snp_file> -i <indel_file>'. See the front page of this github. There's a new link to the v0.2.x documentation.
