### ISSUE TITLE
Installation from source modifies base python package permissions

### ISSUE THREAD

**Issue by erscott** [churchill-lab/g2gtools#3]
It appears g2gtools setup.py changes/overwrites permissions for essential files in the /Users/anaconda/lib/python2.7/site-packages folder. I had to manually change all permissions using chmod -R for this folder to restore IPython.  This also occurs with g2gtools installation in a virtualenv.

Errors will look like:
Permission denied: '/Users/anaconda/lib/python2.7/site-packages/llvmlite-0.16.0-py2.7.egg-info/PKG-INFO'

If this happens to you, check if:
>sudo ipython can start an ipython session.

**Comment by kbchoi-jax** [comment]
There's no way setup.py would possibly change existing permissions if you are not installing it with sudo privilege. Is 'anaconda' your user name? What do the following two commands give you?

$ which conda
$ whoami
